Add multi value metrics support
metricq/metricq-grafana pull request #21
Opened 2021-02-23 14:11 UTC by kinnarr

Fixes #20

2021-02-23 19:15 UTC, tilsche requested changes
Just a tad of inline-documentation what we do and we should be good to go.

2021-02-23 19:15 UTC, tilsche commented on metricq_grafana/amqp.py
> +        if "(" in target_dict["metric"] and ")" in target_dict["metric"]:
```suggestion
        # guess if this is a pattern (regex) to expand and 
        if "(" in target_dict["metric"] and ")" in target_dict["metric"]:
```

2021-02-23 19:16 UTC, tilsche commented
Oh, and what happens if the manager returns an empty list? Maybe we should capture that somehow - can we even?

2021-02-23 20:42 UTC, kinnarr commented
If the manager returns an empty list, it also returns an empty, which results in "no data" being displayed in grafana.

2021-02-24 08:50 UTC, tilsche commented
> If the manager returns an empty list, it also returns an empty, which results in "no data" being displayed in grafana.

I can live with that.

2021-02-24 08:52 UTC, merged